import { Member, Application, ActivityLog, NotificationItem, ClubSettings } from '@/types';

export const KPNS_COLORS = {
  primary: '#3447AA', // Royal Blue
  primaryHover: '#283887',
  secondary: '#FBEAEB', // Powder Pink
  secondaryHover: '#F7D6D8',
  white: '#FFFFFF',
  mainText: '#1F2937',
  secondaryText: '#6B7280',
  border: '#E5E7EB',
  pageBackground: '#F8FAFC',
  success: '#16A34A',
  warning: '#F59E0B',
  error: '#DC2626',
};

export const BLOOD_GROUPS = ['A+', 'A-', 'B+', 'B-', 'AB+', 'AB-', 'O+', 'O-'];

export const DEFAULT_CLUB_SETTINGS: ClubSettings = {
  clubNameBengali: 'খেজুরদা পল্লীউন্নয়ন নারায়ণ সংঘ',
  clubNameEnglish: 'Khejurdaha Pally Unnayan Narayan Sangha (KPNS)',
  tagline: 'একসাথে, এক পরিচয়ে, এক পরিবারের বন্ধনে',
  contactEmail: 'contact@kpns.org.in',
  contactPhone: '+91 98765 43210',
  address: 'Vill: Khejurdaha, P.O: Khejurdaha, Dist: Purba Medinipur, West Bengal - 721401',
  registrationOpen: true,
  autoGenerateMemberId: true,
  memberIdPrefix: 'KPNS',
};

export const INITIAL_MEMBERS: Member[] = [
  {
    id: 'mem-001',
    memberId: 'KPNS75PP26',
    fromNo: '75',
    userId: 'PINTU75',
    role: 'MEMBER',
    status: 'ACTIVE',
    admissionDate: '2026-08-15',
    avatarUrl: '',
    name: 'Pintu Patra',
    fatherName: 'Subhas Patra',
    whatsapp: '9876543210',
    altMobile: '9123456780',
    email: 'pintu.patra@example.com',
    aadhaar: '541278901234',
    bloodGroup: 'O+',
    dob: '1995-09-02', // Today is his birthday in 2026-09-02!
    houseNumber: 'KP-124',
    villageTown: 'Khejurdaha',
    postOffice: 'Khejurdaha',
    policeStation: 'Khejuri',
    city: 'Contai',
    state: 'West Bengal',
    country: 'India',
    pincode: '721401',
    profileCompletion: 85,
    missingFields: ['City missing', 'Police Station missing'],
    createdAt: '2026-08-15T10:00:00Z',
    updatedAt: '2026-09-01T09:15:00Z',
    lastLogin: '2026-09-02T08:30:00Z',
  },
  {
    id: 'mem-002',
    memberId: 'KPNS01AM20',
    fromNo: '01',
    userId: 'ADMIN_KPNS',
    role: 'ADMIN',
    status: 'ACTIVE',
    admissionDate: '2020-01-26',
    name: 'Arup Maiti (Admin)',
    fatherName: 'Nirod Maiti',
    whatsapp: '9832109876',
    altMobile: '9434567890',
    email: 'admin@kpns.org.in',
    aadhaar: '654321098765',
    bloodGroup: 'A+',
    dob: '1988-04-14',
    houseNumber: 'H-01',
    villageTown: 'Khejurdaha',
    postOffice: 'Khejurdaha',
    policeStation: 'Khejuri',
    city: 'Contai',
    state: 'West Bengal',
    country: 'India',
    pincode: '721401',
    profileCompletion: 100,
    missingFields: [],
    createdAt: '2020-01-26T10:00:00Z',
    updatedAt: '2026-09-01T10:32:00Z',
    lastLogin: '2026-09-02T13:45:00Z',
  },
  {
    id: 'mem-003',
    memberId: 'KPNS88RM25',
    fromNo: '88',
    userId: 'RAJA88',
    role: 'MEMBER',
    status: 'ACTIVE',
    admissionDate: '2025-11-10',
    name: 'Raja Mukherjee',
    fatherName: 'Bimal Mukherjee',
    whatsapp: '9830012345',
    email: 'raja.mukherjee@example.com',
    bloodGroup: 'B+',
    dob: '1992-09-05', // Birthday this week
    villageTown: 'Khejurdaha',
    postOffice: 'Khejurdaha',
    policeStation: 'Khejuri',
    city: 'Contai',
    state: 'West Bengal',
    country: 'India',
    pincode: '721401',
    profileCompletion: 92,
    missingFields: ['House Number missing'],
    createdAt: '2025-11-10T12:00:00Z',
    updatedAt: '2026-08-20T11:00:00Z',
  },
  {
    id: 'mem-004',
    memberId: 'KPNS92RG26',
    fromNo: '92',
    userId: 'RANI92',
    role: 'MEMBER',
    status: 'ACTIVE',
    admissionDate: '2026-02-14',
    name: 'Rani Ghosh',
    fatherName: 'Gopal Ghosh',
    whatsapp: '9871122334',
    email: 'rani.ghosh@example.com',
    bloodGroup: 'AB+',
    dob: '1998-09-20', // Birthday this month
    villageTown: 'Khejurdaha',
    state: 'West Bengal',
    country: 'India',
    pincode: '721401',
    profileCompletion: 70,
    missingFields: ['Email ID missing', 'Post Office missing', 'City missing'],
    createdAt: '2026-02-14T09:30:00Z',
    updatedAt: '2026-07-10T14:15:00Z',
  },
  {
    id: 'mem-005',
    memberId: 'KPNS45SK24',
    fromNo: '45',
    userId: 'SOUMEN45',
    role: 'MEMBER',
    status: 'INACTIVE',
    admissionDate: '2024-05-01',
    name: 'Soumen Karan',
    fatherName: 'Tarapada Karan',
    whatsapp: '9733445566',
    email: 'soumen.k@example.com',
    bloodGroup: 'O-',
    dob: '1990-12-05',
    villageTown: 'Bhograi',
    city: 'Jaleswar',
    state: 'Odisha',
    country: 'India',
    pincode: '756038',
    profileCompletion: 80,
    missingFields: ['Aadhaar missing', 'Post Office missing'],
    createdAt: '2024-05-01T08:00:00Z',
    updatedAt: '2025-01-15T16:00:00Z',
  },
];

export const INITIAL_APPLICATIONS: Application[] = [
  {
    id: 'KPNS-APP-2026-0001',
    status: 'PENDING',
    appliedDate: '2026-09-01',
    name: 'Debasish Jana',
    fatherName: 'Bhabesh Jana',
    whatsapp: '9876501234',
    altMobile: '9876501235',
    email: 'debasish.jana@example.com',
    aadhaar: '789012345678',
    bloodGroup: 'O+',
    dob: '1996-03-15',
    houseNumber: '12-B',
    villageTown: 'Khejurdaha',
    postOffice: 'Khejurdaha',
    policeStation: 'Khejuri',
    city: 'Contai',
    state: 'West Bengal',
    country: 'India',
    pincode: '721401',
  },
  {
    id: 'KPNS-APP-2026-0002',
    status: 'PENDING',
    appliedDate: '2026-09-02',
    name: 'Mousumi Das',
    fatherName: 'Prabir Das',
    whatsapp: '9832456789',
    email: 'mousumi.das@example.com',
    bloodGroup: 'B+',
    dob: '1999-11-22',
    villageTown: 'Kamarda',
    postOffice: 'Kamarda',
    policeStation: 'Khejuri',
    city: 'Contai',
    state: 'West Bengal',
    country: 'India',
    pincode: '721430',
  },
  {
    id: 'KPNS-APP-2026-0003',
    status: 'APPROVED',
    appliedDate: '2026-08-28',
    name: 'Pintu Patra',
    fatherName: 'Subhas Patra',
    whatsapp: '9876543210',
    email: 'pintu.patra@example.com',
    bloodGroup: 'O+',
    dob: '1995-09-02',
    villageTown: 'Khejurdaha',
    postOffice: 'Khejurdaha',
    policeStation: 'Khejuri',
    city: 'Contai',
    state: 'West Bengal',
    country: 'India',
    pincode: '721401',
    fromNo: '75',
    memberId: 'KPNS75PP26',
    admissionDate: '2026-08-15',
    userId: 'PINTU75',
    reviewedBy: 'ADMIN',
    reviewedAt: '2026-08-28T18:20:00Z',
  },
  {
    id: 'KPNS-APP-2026-0004',
    status: 'REJECTED',
    appliedDate: '2026-08-25',
    name: 'Ramesh Sen',
    fatherName: 'Anadi Sen',
    whatsapp: '9433112233',
    email: 'ramesh.sen@example.com',
    bloodGroup: 'A-',
    dob: '1985-06-18',
    villageTown: 'Kolkata',
    state: 'West Bengal',
    country: 'India',
    pincode: '700001',
    rejectionReason: 'Applicant resides outside local community jurisdiction.',
    reviewedBy: 'ADMIN',
    reviewedAt: '2026-08-26T14:10:00Z',
  },
];

export const INITIAL_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'notif-1',
    title: 'Profile updated successfully',
    description: 'Your profile information was updated.',
    date: 'Today, 10:32 AM',
    read: false,
    type: 'info',
  },
  {
    id: 'notif-2',
    title: 'Membership approved',
    description: 'Your KPNS Membership has been officially approved.',
    date: '28-08-2026',
    read: true,
    type: 'success',
  },
  {
    id: 'notif-3',
    title: 'Welcome to KPNS',
    description: 'Welcome to খেজুরদা পল্লীউন্নয়ন নারায়ণ সংঘ digital portal.',
    date: '28-08-2026',
    read: true,
    type: 'info',
  },
  {
    id: 'notif-4',
    title: 'Upcoming Blood Donation Camp',
    description: 'Annual Blood Donation & Health Camp on 2nd October 2026 at Club premises.',
    date: '25-08-2026',
    read: true,
    type: 'warning',
  },
];

export const INITIAL_ACTIVITY_LOGS: ActivityLog[] = [
  {
    id: 'log-1',
    timestamp: '01-09-2026 10:32',
    user: 'ADMIN',
    role: 'Admin',
    action: 'Updated member KPNS75PP26',
    memberId: 'KPNS75PP26',
    details: 'Verified Aadhaar and updated contact information.',
  },
  {
    id: 'log-2',
    timestamp: '01-09-2026 09:15',
    user: 'PINTU75',
    role: 'Member',
    action: 'Updated profile',
    memberId: 'KPNS75PP26',
    details: 'Updated Father Name and Village/Town details.',
  },
  {
    id: 'log-3',
    timestamp: '31-08-2026 18:20',
    user: 'ADMIN',
    role: 'Admin',
    action: 'Approved KPNS-APP-2026-0003',
    details: 'Assigned Member ID: KPNS75PP26, Form No: 75.',
  },
  {
    id: 'log-4',
    timestamp: '30-08-2026 14:00',
    user: 'ADMIN',
    role: 'Admin',
    action: 'Imported 15 new members from CSV',
    details: 'Batch import processed with 0 duplicates.',
  },
  {
    id: 'log-5',
    timestamp: '28-08-2026 11:30',
    user: 'ADMIN',
    role: 'Admin',
    action: 'Updated Club Settings',
    details: 'Updated club contact phone number.',
  },
];
