export interface CupPhoto {
  id: string;
  title: string;
  caption: string;
  category: string;
  imageUrl: string;
  facebookUrl: string;
}

export interface CupYearData {
  year: number;
  edition: string;
  season: string;
  champion: string;
  runnersUp: string;
  teamsCount: number;
  venue: string;
  description: string;
  facebookAlbumUrl: string;
  photos: CupPhoto[];
}

export interface BoishakhiVideo {
  id: string;
  title: string;
  bengaliTitle: string;
  category: string;
  performer?: string;
  duration: string;
  youtubeId: string;
  thumbnailUrl: string;
  youtubeUrl: string;
}

export interface BoishakhiYearData {
  bengaliYear: string;
  gregorianYear: number;
  edition: string;
  occasion: string;
  theme: string;
  venue: string;
  description: string;
  playlistUrl: string;
  playlistThumbnail: string;
  videos: BoishakhiVideo[];
}

// ─────────────────────────────────────────────────────────────────────────────
// KPNS CUP DATA (2013 – 2025)
// ─────────────────────────────────────────────────────────────────────────────
export const KPNS_CUP_YEARS: CupYearData[] = [
  {
    year: 2025,
    edition: '13th Edition',
    season: 'Winter 2025 (Day-Night)',
    champion: 'PANCHRUL 9STAR CLUB',
    runnersUp: 'SK 9STAR CLUB BALIGHAI',
    teamsCount: 16,
    venue: 'Khejurda, Narayan Mondir Ground, Purba Medinipur',
    description: 'The 13th edition of the Day-Night Cricket Tournament brought together top grassroots cricket clubs across Purba Medinipur under dazzling floodlights, with over 5,000 enthusiastic local supporters witnessing thrilling night matches.',
    facebookAlbumUrl: 'https://www.facebook.com/kpns.club/photos',
    photos: [
      {
        id: 'c2025-1',
        title: 'Trophy Presentation Ceremony',
        caption: 'KPNS President & Committee handing over the coveted Champion Trophy to Panchrul 9Star Club.',
        category: 'Awards & Honors',
        imageUrl: 'https://lh3.googleusercontent.com/d/1-Hx-9wKvcC2LVE29m087EC_RMSx7UsuQ',
        facebookUrl: 'https://www.facebook.com/kpns.club/photos',
      },
      {
        id: 'c2025-2',
        title: 'High-Octane Final Match Action',
        caption: 'Electrifying bowling and boundary defense in the final over under floodlights.',
        category: 'Match Action',
        imageUrl: 'https://lh3.googleusercontent.com/d/1lXo84m6XT_KmW05pei0qbj2zDyS9zA1T',
        facebookUrl: 'https://www.facebook.com/kpns.club/photos',
      },
      {
        id: 'c2025-3',
        title: 'Champion Squad Victory Lap',
        caption: 'Panchrul 9Star Club celebrating the championship win under the floodlit stadium with passionate fans.',
        category: 'Celebration',
        imageUrl: 'https://images.unsplash.com/photo-1540747913346-19e32dc3e97e?w=800&auto=format&fit=crop&q=80',
        facebookUrl: 'https://www.facebook.com/kpns.club/photos',
      },
      {
        id: 'c2025-4',
        title: 'Roaring Rural Spectators',
        caption: 'Thousands of spectators cheering along the boundary lines under the evening floodlights.',
        category: 'Community & Fans',
        imageUrl: 'https://images.unsplash.com/photo-1516475429286-465d815a0df7?w=800&auto=format&fit=crop&q=80',
        facebookUrl: 'https://www.facebook.com/kpns.club/photos',
      },
    ],
  },
  {
    year: 2024,
    edition: '12th Edition',
    season: 'Winter 2024 (Day-Night)',
    champion: 'Contai Warriors CC',
    runnersUp: 'Khejurda Narayan Sangha Cricket XI',
    teamsCount: 16,
    venue: 'Khejurda Stadium Ground',
    description: 'A fiercely contested Day-Night Cricket Tournament featuring high-scoring innings, hat-tricks, and superb fielding under dazzling floodlights.',
    facebookAlbumUrl: 'https://www.facebook.com/kpns.club/photos',
    photos: [
      {
        id: 'c2024-1',
        title: 'Grand Inauguration Parade & Toss',
        caption: 'Team captains at the coin toss with stadium floodlights lighting up the ground.',
        category: 'Opening Ceremony',
        imageUrl: 'https://images.unsplash.com/photo-1540747913346-19e32dc3e97e?w=800&auto=format&fit=crop&q=80',
        facebookUrl: 'https://www.facebook.com/kpns.club/photos',
      },
      {
        id: 'c2024-2',
        title: 'Towering Sixer over Mid-Wicket',
        caption: 'Spectacular batting display in the semi-final under floodlights.',
        category: 'Match Action',
        imageUrl: 'https://images.unsplash.com/photo-1531415074868-036b1c57e359?w=800&auto=format&fit=crop&q=80',
        facebookUrl: 'https://www.facebook.com/kpns.club/photos',
      },
      {
        id: 'c2024-3',
        title: 'Man of the Match & Fairplay Awards',
        caption: 'Honoring disciplined sportsmanship and exceptional all-round performances.',
        category: 'Fair Play',
        imageUrl: 'https://images.unsplash.com/photo-1526232761682-d26e03ac148e?w=800&auto=format&fit=crop&q=80',
        facebookUrl: 'https://www.facebook.com/kpns.club/photos',
      },
    ],
  },
  {
    year: 2023,
    edition: '11th Edition',
    season: 'Winter 2023 (Day-Night)',
    champion: 'Khejurda Royal Challengers CC',
    runnersUp: 'Ramnagar Strikers CC',
    teamsCount: 16,
    venue: 'Khejurda High School Ground',
    description: 'Celebrating the 10th anniversary edition of the Day-Night Cricket Tournament with record attendance, white cricket balls, and festive floodlit cricket nights.',
    facebookAlbumUrl: 'https://www.facebook.com/kpns.club/photos',
    photos: [
      {
        id: 'c2023-1',
        title: 'Floodlit Stadium Atmosphere',
        caption: 'Packed spectator stands as the host team lift the trophy under night floodlights.',
        category: 'Celebration',
        imageUrl: 'https://images.unsplash.com/photo-1516475429286-465d815a0df7?w=800&auto=format&fit=crop&q=80',
        facebookUrl: 'https://www.facebook.com/kpns.club/photos',
      },
      {
        id: 'c2023-2',
        title: 'Man of the Series Felicitation',
        caption: 'Awarding the tournament top run-scorer and wicket-taker with official mementos.',
        category: 'Awards & Honors',
        imageUrl: 'https://images.unsplash.com/photo-1526232761682-d26e03ac148e?w=800&auto=format&fit=crop&q=80',
        facebookUrl: 'https://www.facebook.com/kpns.club/photos',
      },
    ],
  },
  {
    year: 2022,
    edition: '10th Edition',
    season: 'Winter 2022 (Day-Night)',
    champion: 'Digha Coastal Cricket Club',
    runnersUp: 'Khejurda Young Challengers CC',
    teamsCount: 16,
    venue: 'Khejurda Stadium Ground',
    description: 'A grand return of floodlit night cricket, marked by high energy, exciting super-overs, and roaring support from neighboring villages.',
    facebookAlbumUrl: 'https://www.facebook.com/kpns.club/photos',
    photos: [
      {
        id: 'c2022-1',
        title: 'Final Over Jubilation',
        caption: 'Players celebrating the championship title after hitting the winning boundary in the last over.',
        category: 'Celebration',
        imageUrl: 'https://images.unsplash.com/photo-1540747913346-19e32dc3e97e?w=800&auto=format&fit=crop&q=80',
        facebookUrl: 'https://www.facebook.com/kpns.club/photos',
      },
      {
        id: 'c2022-2',
        title: 'Stump-Uprooting Yorker Delivery',
        caption: 'Fast bowler taking a match-turning wicket under stadium lights.',
        category: 'Match Action',
        imageUrl: 'https://images.unsplash.com/photo-1531415074868-036b1c57e359?w=800&auto=format&fit=crop&q=80',
        facebookUrl: 'https://www.facebook.com/kpns.club/photos',
      },
    ],
  },
  {
    year: 2021,
    edition: '9th Edition',
    season: 'Winter 2021 (Day-Night)',
    champion: 'Egra Central Cricket Club',
    runnersUp: 'Khejurda Palliunnyayan CC',
    teamsCount: 12,
    venue: 'Khejurda Ground',
    description: 'Organized with discipline and enthusiasm, bringing joy and sportsmanship to local cricket lovers through competitive floodlit matches.',
    facebookAlbumUrl: 'https://www.facebook.com/kpns.club/photos',
    photos: [
      {
        id: 'c2021-1',
        title: 'Tournament Shield Presentation',
        caption: 'Club elders and village seniors conferring the trophy to Egra champions under the floodlights.',
        category: 'Awards & Honors',
        imageUrl: 'https://images.unsplash.com/photo-1526232761682-d26e03ac148e?w=800&auto=format&fit=crop&q=80',
        facebookUrl: 'https://www.facebook.com/kpns.club/photos',
      },
    ],
  },
  {
    year: 2020,
    edition: '8th Edition',
    season: 'Early 2020 (Day-Night)',
    champion: 'Khejurda United CC',
    runnersUp: 'Belda Pioneer Cricket XI',
    teamsCount: 16,
    venue: 'Khejurda High School Ground',
    description: 'A memorable floodlit cricket edition held in January 2020, showcasing extraordinary spin bowling and nail-biting finishes.',
    facebookAlbumUrl: 'https://www.facebook.com/kpns.club/photos',
    photos: [
      {
        id: 'c2020-1',
        title: 'Winning Six Celebration by Khejurda United',
        caption: 'Striking a magnificent six over cover to seal the 2020 title.',
        category: 'Match Action',
        imageUrl: 'https://images.unsplash.com/photo-1531415074868-036b1c57e359?w=800&auto=format&fit=crop&q=80',
        facebookUrl: 'https://www.facebook.com/kpns.club/photos',
      },
    ],
  },
  {
    year: 2019,
    edition: '7th Edition',
    season: 'Winter 2019 (Day-Night)',
    champion: 'Purba Medinipur Cricket Academy',
    runnersUp: 'Khejurda Blue Tigers CC',
    teamsCount: 16,
    venue: 'Khejurda Stadium Ground',
    description: 'Featured record attendance with live commentary in Bengali, DJ sound cheering, and unforgettable floodlit cricket under clear winter skies.',
    facebookAlbumUrl: 'https://www.facebook.com/kpns.club/photos',
    photos: [
      {
        id: 'c2019-1',
        title: 'Opening Night Lineup',
        caption: 'Cricket team captains taking the tournament pledge of fairplay under floodlights.',
        category: 'Opening Ceremony',
        imageUrl: 'https://images.unsplash.com/photo-1540747913346-19e32dc3e97e?w=800&auto=format&fit=crop&q=80',
        facebookUrl: 'https://www.facebook.com/kpns.club/photos',
      },
    ],
  },
  {
    year: 2018,
    edition: '6th Edition',
    season: 'Winter 2018 (Day-Night)',
    champion: 'Khejurda Palliunnyayan CC',
    runnersUp: 'Bhagabanpur Cricket Club',
    teamsCount: 16,
    venue: 'Khejurda High School Ground',
    description: 'An electrifying final decided on the very last ball, cementing KPNS CUP as the most prestigious Day-Night Cricket trophy in Egra subdivision.',
    facebookAlbumUrl: 'https://www.facebook.com/kpns.club/photos',
    photos: [
      {
        id: 'c2018-1',
        title: 'Last-Ball Climax under Floodlights',
        caption: 'Two runs needed off the last ball — Khejurda pulls off a thrilling victory!',
        category: 'Match Action',
        imageUrl: 'https://images.unsplash.com/photo-1531415074868-036b1c57e359?w=800&auto=format&fit=crop&q=80',
        facebookUrl: 'https://www.facebook.com/kpns.club/photos',
      },
    ],
  },
  {
    year: 2017,
    edition: '5th Edition',
    season: 'Winter 2017 (Day-Night)',
    champion: 'Contai Youth Cricket Club',
    runnersUp: 'Khejurda Narayan Sangha CC',
    teamsCount: 16,
    venue: 'Khejurda Stadium Ground',
    description: 'Marked the 5th milestone year of KPNS CUP Day-Night Cricket with honors for foundational organizers and veteran cricketers.',
    facebookAlbumUrl: 'https://www.facebook.com/kpns.club/photos',
    photos: [
      {
        id: 'c2017-1',
        title: '5th Year Jubilee Ceremony',
        caption: 'Veterans and senior cricketers felicitated on the field under evening lights.',
        category: 'Awards & Honors',
        imageUrl: 'https://images.unsplash.com/photo-1526232761682-d26e03ac148e?w=800&auto=format&fit=crop&q=80',
        facebookUrl: 'https://www.facebook.com/kpns.club/photos',
      },
    ],
  },
  {
    year: 2016,
    edition: '4th Edition',
    season: 'Winter 2016 (Day-Night)',
    champion: 'Egra City Cricket Club',
    runnersUp: 'Kharagpur Town Cricket XI',
    teamsCount: 16,
    venue: 'Khejurda Ground',
    description: 'Expanded inter-district entries including premier cricket teams from Paschim Medinipur, creating legendary night matches.',
    facebookAlbumUrl: 'https://www.facebook.com/kpns.club/photos',
    photos: [
      {
        id: 'c2016-1',
        title: 'Straight Drive Boundary',
        caption: 'Flawless straight drive through the covers in the opening group match.',
        category: 'Match Action',
        imageUrl: 'https://images.unsplash.com/photo-1531415074868-036b1c57e359?w=800&auto=format&fit=crop&q=80',
        facebookUrl: 'https://www.facebook.com/kpns.club/photos',
      },
    ],
  },
  {
    year: 2015,
    edition: '3rd Edition',
    season: 'Winter 2015 (Day-Night)',
    champion: 'Khejurda Narayan Sangha CC',
    runnersUp: 'Potashpur Cricket Club',
    teamsCount: 12,
    venue: 'Khejurda High School Ground',
    description: 'Passionate clashes with local village youth stepping forward as star batsmen and fast bowlers under floodlights.',
    facebookAlbumUrl: 'https://www.facebook.com/kpns.club/photos',
    photos: [
      {
        id: 'c2015-1',
        title: 'Youth Cricket Squad Triumph',
        caption: 'The young squad holding the trophy alongside proud village mentors under floodlights.',
        category: 'Celebration',
        imageUrl: 'https://images.unsplash.com/photo-1540747913346-19e32dc3e97e?w=800&auto=format&fit=crop&q=80',
        facebookUrl: 'https://www.facebook.com/kpns.club/photos',
      },
    ],
  },
  {
    year: 2014,
    edition: '2nd Edition',
    season: 'Winter 2014 (Day-Night)',
    champion: 'Egra Rural Stars CC',
    runnersUp: 'Khejurda Blue Cricket XI',
    teamsCount: 12,
    venue: 'Khejurda Ground',
    description: 'Consolidated the tournament as an eagerly awaited yearly floodlit event following the grand success of the inaugural edition.',
    facebookAlbumUrl: 'https://www.facebook.com/kpns.club/photos',
    photos: [
      {
        id: 'c2014-1',
        title: 'Flying Catch at Point',
        caption: 'Stunning one-handed diving catch under the floodlights in the semi-finals.',
        category: 'Match Action',
        imageUrl: 'https://images.unsplash.com/photo-1531415074868-036b1c57e359?w=800&auto=format&fit=crop&q=80',
        facebookUrl: 'https://www.facebook.com/kpns.club/photos',
      },
    ],
  },
  {
    year: 2013,
    edition: '1st Inaugural Edition',
    season: 'Winter 2013 (Day-Night)',
    champion: 'Khejurda Palliunnyayan Narayan Sangha CC',
    runnersUp: 'Egra Friends Cricket XI',
    teamsCount: 8,
    venue: 'Khejurda High School Ground',
    description: 'The historic beginning of KPNS CUP in 2013, born from the vision to unite the youth, promote sportsmanship, and introduce thrilling Day-Night floodlit cricket to our rural community.',
    facebookAlbumUrl: 'https://www.facebook.com/kpns.club/photos',
    photos: [
      {
        id: 'c2013-1',
        title: 'Before Final Match',
        caption: 'Teams gathering at the ground ahead of the historic inaugural KPNS CUP final match in 2013.',
        category: 'Match Preparation',
        imageUrl: 'https://lh3.googleusercontent.com/d/1qd4MmdkxeEZxRG5ZcBXcNWPihaWBCybS',
        facebookUrl: 'https://www.facebook.com/kpns.club/photos',
      },
      {
        id: 'c2013-2',
        title: 'Before Starting',
        caption: 'Players and organisers assembled at the ground before the commencement of the 1st KPNS CUP tournament.',
        category: 'Opening Ceremony',
        imageUrl: 'https://lh3.googleusercontent.com/d/1C5o8W1hM5lHIXx47cOmOEgLNDX8a17VV',
        facebookUrl: 'https://www.facebook.com/kpns.club/photos',
      },
      {
        id: 'c2013-3',
        title: 'Champion Team',
        caption: 'The inaugural KPNS CUP 2013 champion team — Khejurda Palliunnyayan Narayan Sangha CC — celebrating their historic title.',
        category: 'Celebration',
        imageUrl: 'https://lh3.googleusercontent.com/d/1skD-r2pUQaGFnUMwRuALq-7LFzuNCRr2',
        facebookUrl: 'https://www.facebook.com/kpns.club/photos',
      },
      {
        id: 'c2013-4',
        title: 'The KPNS CUP Trophy',
        caption: 'The coveted KPNS CUP trophy — symbol of cricketing excellence and community pride since 2013.',
        category: 'Trophy',
        imageUrl: 'https://lh3.googleusercontent.com/d/1L0WlGZ0WpiDctDKZhgIu7AZ5385nX2TF',
        facebookUrl: 'https://www.facebook.com/kpns.club/photos',
      },
      {
        id: 'c2013-5',
        title: 'Tournament Ground',
        caption: 'Khejurda High School Ground — the birthplace of the KPNS CUP Day-Night Cricket Tournament in 2013.',
        category: 'Venue',
        imageUrl: 'https://lh3.googleusercontent.com/d/1whJXWUd9BWQJTFV_LG25YbgqgJr6SrS-',
        facebookUrl: 'https://www.facebook.com/kpns.club/photos',
      },
    ],
  },
];

// ─────────────────────────────────────────────────────────────────────────────
// বৈশাখী সন্ধ্যা DATA (১৪১৯ – ১৪৩২ বঙ্গাব্দ)
// ─────────────────────────────────────────────────────────────────────────────
export const BOISHAKHI_YEARS: BoishakhiYearData[] = [
  {
    bengaliYear: '১৪৩২',
    gregorianYear: 2025,
    edition: '১৪তম বর্ষ (14th Year)',
    occasion: 'পহেলা বৈশাখ ১৪৩২ শুভ নববর্ষ সাংস্কৃতিক মহোৎসব ও মেলা',
    theme: 'ঐতিহ্য ও তারুণ্যের উৎসবমুখর বৈশাখী মিলনমেলা',
    venue: 'খেজুরদা নারায়ণ সংঘ মুক্তমঞ্চ প্রাঙ্গণ',
    description: '১৪৩২ বঙ্গাব্দের বর্ণাঢ্য আয়োজনে লাইভ কনসার্ট, ছদ্মবেশ প্রতিযোগিতা, কৌতুক নৃত্য ও মনোজ্ঞ সাংস্কৃতিক পরিবেশনা সহ ২৪টি পর্ব অনুষ্ঠিত হয়।',
    playlistUrl: 'https://www.youtube.com/playlist?list=PLo4mBgpHrEi-JpnB0JJ9a_nX7pWxlQfGk',
    playlistThumbnail: 'https://img.youtube.com/vi/oquLVZgywSg/hqdefault.jpg',
    videos: [
      {
        id: 'b১৪৩২-1',
        title: "Live concert || বৈশাখী মেলা ১৪৩২ || KPNS",
        bengaliTitle: "Live concert || বৈশাখী মেলা ১৪৩২ || KPNS",
        category: 'সঙ্গীতানুষ্ঠান',
        performer: 'কে.পি.এন.এস সাংস্কৃতিক শিল্পী ও দল',
        duration: 'YouTube',
        youtubeId: 'oquLVZgywSg',
        thumbnailUrl: 'https://img.youtube.com/vi/oquLVZgywSg/hqdefault.jpg',
        youtubeUrl: 'https://www.youtube.com/watch?v=oquLVZgywSg',
      },
      {
        id: 'b১৪৩২-2',
        title: "ছদ্মবেশ প্রতিযোগিতা || বৈশাখী মেলা ১৪৩২ || KPNS",
        bengaliTitle: "ছদ্মবেশ প্রতিযোগিতা || বৈশাখী মেলা ১৪৩২ || KPNS",
        category: 'সাংস্কৃতিক অনুষ্ঠান',
        performer: 'কে.পি.এন.এস সাংস্কৃতিক শিল্পী ও দল',
        duration: 'YouTube',
        youtubeId: 'vbSYuiDCiK8',
        thumbnailUrl: 'https://img.youtube.com/vi/vbSYuiDCiK8/hqdefault.jpg',
        youtubeUrl: 'https://www.youtube.com/watch?v=vbSYuiDCiK8',
      },
      {
        id: 'b১৪৩২-3',
        title: "উপসংহার || বৈশাখী মেলা ১৪৩২ || KPNS",
        bengaliTitle: "উপসংহার || বৈশাখী মেলা ১৪৩২ || KPNS",
        category: 'সাংস্কৃতিক অনুষ্ঠান',
        performer: 'কে.পি.এন.এস সাংস্কৃতিক শিল্পী ও দল',
        duration: 'YouTube',
        youtubeId: 't8yQu-x9128',
        thumbnailUrl: 'https://img.youtube.com/vi/t8yQu-x9128/hqdefault.jpg',
        youtubeUrl: 'https://www.youtube.com/watch?v=t8yQu-x9128',
      },
      {
        id: 'b১৪৩২-4',
        title: "COMEDY DANCE || বৈশাখী মেলা ১৪৩২ || KPNS",
        bengaliTitle: "COMEDY DANCE || বৈশাখী মেলা ১৪৩২ || KPNS",
        category: 'নৃত্য পরিবেশনা',
        performer: 'কে.পি.এন.এস সাংস্কৃতিক শিল্পী ও দল',
        duration: 'YouTube',
        youtubeId: '0Dcx29P68JU',
        thumbnailUrl: 'https://img.youtube.com/vi/0Dcx29P68JU/hqdefault.jpg',
        youtubeUrl: 'https://www.youtube.com/watch?v=0Dcx29P68JU',
      },
      {
        id: 'b১৪৩২-5',
        title: "সঞ্চালিকার মনের কথা || বৈশাখী মেলা ১৪৩২ || KPNS",
        bengaliTitle: "সঞ্চালিকার মনের কথা || বৈশাখী মেলা ১৪৩২ || KPNS",
        category: 'সাংস্কৃতিক অনুষ্ঠান',
        performer: 'কে.পি.এন.এস সাংস্কৃতিক শিল্পী ও দল',
        duration: 'YouTube',
        youtubeId: 'dpWTSFwKD44',
        thumbnailUrl: 'https://img.youtube.com/vi/dpWTSFwKD44/hqdefault.jpg',
        youtubeUrl: 'https://www.youtube.com/watch?v=dpWTSFwKD44',
      },
      {
        id: 'b১৪৩২-6',
        title: "NON STOP MIX || বৈশাখী মেলা ১৪৩২ || KPNS",
        bengaliTitle: "NON STOP MIX || বৈশাখী মেলা ১৪৩২ || KPNS",
        category: 'সাংস্কৃতিক অনুষ্ঠান',
        performer: 'কে.পি.এন.এস সাংস্কৃতিক শিল্পী ও দল',
        duration: 'YouTube',
        youtubeId: 'wbICyXtnPc8',
        thumbnailUrl: 'https://img.youtube.com/vi/wbICyXtnPc8/hqdefault.jpg',
        youtubeUrl: 'https://www.youtube.com/watch?v=wbICyXtnPc8',
      },
      {
        id: 'b১৪৩২-7',
        title: "ଓଡିଆ ଗୀତ || বৈশাখী মেলা ১৪৩২ || KPNS",
        bengaliTitle: "ଓଡିଆ ଗୀତ || বৈশাখী মেলা ১৪৩২ || KPNS",
        category: 'সাংস্কৃতিক অনুষ্ঠান',
        performer: 'কে.পি.এন.এস সাংস্কৃতিক শিল্পী ও দল',
        duration: 'YouTube',
        youtubeId: 'C4IJ7ONwmEI',
        thumbnailUrl: 'https://img.youtube.com/vi/C4IJ7ONwmEI/hqdefault.jpg',
        youtubeUrl: 'https://www.youtube.com/watch?v=C4IJ7ONwmEI',
      },
      {
        id: 'b১৪৩২-8',
        title: "নাচ নাগিনী নাচ রে || বৈশাখী মেলা ১৪৩২ || KPNS",
        bengaliTitle: "নাচ নাগিনী নাচ রে || বৈশাখী মেলা ১৪৩২ || KPNS",
        category: 'সাংস্কৃতিক অনুষ্ঠান',
        performer: 'কে.পি.এন.এস সাংস্কৃতিক শিল্পী ও দল',
        duration: 'YouTube',
        youtubeId: 'RJYOw8GIZJw',
        thumbnailUrl: 'https://img.youtube.com/vi/RJYOw8GIZJw/hqdefault.jpg',
        youtubeUrl: 'https://www.youtube.com/watch?v=RJYOw8GIZJw',
      },
    ],
  },
  {
    bengaliYear: '১৪৩১',
    gregorianYear: 2024,
    edition: '১৩তম বর্ষ (13th Year)',
    occasion: 'পহেলা বৈশাখ ১৪৩১ শুভ নববর্ষ মহোৎসব ও বৈশাখী মেলা',
    theme: 'বাঙালির প্রাণের মেলা ও মিলনসন্ধ্যা',
    venue: 'খেজুরদা নারায়ণ সংঘ মুক্তমঞ্চ প্রাঙ্গণ',
    description: '১৪৩১ বঙ্গাব্দের বৈশাখী সন্ধ্যা হাজারো গ্রামবাসীর উপস্থিতিতে আনন্দমুখর পরিবেশে অনুষ্ঠিত হয়। বাংলা নাটক "ওগো বিষ্ণুপ্রিয়া", নৃত্যনাট্য ও সুরের মূর্ছনায় মুখরিত হয় মুক্তমঞ্চ।',
    playlistUrl: 'https://www.youtube.com/playlist?list=PLo4mBgpHrEi-LAihJY-EMuDluBINjuF8r',
    playlistThumbnail: 'https://img.youtube.com/vi/7iiQ2P1s24s/hqdefault.jpg',
    videos: [
      {
        id: 'b১৪৩১-1',
        title: "ওগো বিষ্ণুপ্রিয়া || Bangla Natok || বৈশাখী মেলা ১৪৩১ || KPNS",
        bengaliTitle: "ওগো বিষ্ণুপ্রিয়া || Bangla Natok || বৈশাখী মেলা ১৪৩১ || KPNS",
        category: 'সাংস্কৃতিক অনুষ্ঠান',
        performer: 'কে.পি.এন.এস সাংস্কৃতিক শিল্পী ও দল',
        duration: 'YouTube',
        youtubeId: '7iiQ2P1s24s',
        thumbnailUrl: 'https://img.youtube.com/vi/7iiQ2P1s24s/hqdefault.jpg',
        youtubeUrl: 'https://www.youtube.com/watch?v=7iiQ2P1s24s',
      },
      {
        id: 'b১৪৩১-2',
        title: "Lungi Dance || বৈশাখী মেলা ১৪৩১ || KPNS",
        bengaliTitle: "Lungi Dance || বৈশাখী মেলা ১৪৩১ || KPNS",
        category: 'সাংস্কৃতিক অনুষ্ঠান',
        performer: 'কে.পি.এন.এস সাংস্কৃতিক শিল্পী ও দল',
        duration: 'YouTube',
        youtubeId: '-UQBkIs3pKc',
        thumbnailUrl: 'https://img.youtube.com/vi/-UQBkIs3pKc/hqdefault.jpg',
        youtubeUrl: 'https://www.youtube.com/watch?v=-UQBkIs3pKc',
      },
      {
        id: 'b১৪৩১-3',
        title: "Saami Saami || বৈশাখী মেলা ১৪৩১ || KPNS",
        bengaliTitle: "Saami Saami || বৈশাখী মেলা ১৪৩১ || KPNS",
        category: 'সাংস্কৃতিক অনুষ্ঠান',
        performer: 'কে.পি.এন.এস সাংস্কৃতিক শিল্পী ও দল',
        duration: 'YouTube',
        youtubeId: 'K3hUHoWIBmw',
        thumbnailUrl: 'https://img.youtube.com/vi/K3hUHoWIBmw/hqdefault.jpg',
        youtubeUrl: 'https://www.youtube.com/watch?v=K3hUHoWIBmw',
      },
      {
        id: 'b১৪৩১-4',
        title: "Chota Bachcha Jaan Ke || বৈশাখী মেলা ১৪৩১ || KPNS",
        bengaliTitle: "Chota Bachcha Jaan Ke || বৈশাখী মেলা ১৪৩১ || KPNS",
        category: 'সাংস্কৃতিক অনুষ্ঠান',
        performer: 'কে.পি.এন.এস সাংস্কৃতিক শিল্পী ও দল',
        duration: 'YouTube',
        youtubeId: 'gV39P3Gcmsg',
        thumbnailUrl: 'https://img.youtube.com/vi/gV39P3Gcmsg/hqdefault.jpg',
        youtubeUrl: 'https://www.youtube.com/watch?v=gV39P3Gcmsg',
      },
      {
        id: 'b১৪৩১-5',
        title: "Hayo Rabba Hayo Rabba || বৈশাখী মেলা ১৪৩১ || KPNS",
        bengaliTitle: "Hayo Rabba Hayo Rabba || বৈশাখী মেলা ১৪৩১ || KPNS",
        category: 'সাংস্কৃতিক অনুষ্ঠান',
        performer: 'কে.পি.এন.এস সাংস্কৃতিক শিল্পী ও দল',
        duration: 'YouTube',
        youtubeId: 'cIUFygQyH8Y',
        thumbnailUrl: 'https://img.youtube.com/vi/cIUFygQyH8Y/hqdefault.jpg',
        youtubeUrl: 'https://www.youtube.com/watch?v=cIUFygQyH8Y',
      },
      {
        id: 'b১৪৩১-6',
        title: "Suna Jhulanare Jhuluchi || বৈশাখী মেলা ১৪৩১ || KPNS",
        bengaliTitle: "Suna Jhulanare Jhuluchi || বৈশাখী মেলা ১৪৩১ || KPNS",
        category: 'সাংস্কৃতিক অনুষ্ঠান',
        performer: 'কে.পি.এন.এস সাংস্কৃতিক শিল্পী ও দল',
        duration: 'YouTube',
        youtubeId: 'nxLt7BuYTVE',
        thumbnailUrl: 'https://img.youtube.com/vi/nxLt7BuYTVE/hqdefault.jpg',
        youtubeUrl: 'https://www.youtube.com/watch?v=nxLt7BuYTVE',
      },
      {
        id: 'b১৪৩১-7',
        title: "বাবা আমার কি বিয়ে হবে না? || বৈশাখী মেলা ১৪৩১ || KPNS",
        bengaliTitle: "বাবা আমার কি বিয়ে হবে না? || বৈশাখী মেলা ১৪৩১ || KPNS",
        category: 'সাংস্কৃতিক অনুষ্ঠান',
        performer: 'কে.পি.এন.এস সাংস্কৃতিক শিল্পী ও দল',
        duration: 'YouTube',
        youtubeId: 'jpODaKjrR64',
        thumbnailUrl: 'https://img.youtube.com/vi/jpODaKjrR64/hqdefault.jpg',
        youtubeUrl: 'https://www.youtube.com/watch?v=jpODaKjrR64',
      },
      {
        id: 'b১৪৩১-8',
        title: "CHAK DE INDIA || বৈশাখী মেলা ১৪৩১ || KPNS",
        bengaliTitle: "CHAK DE INDIA || বৈশাখী মেলা ১৪৩১ || KPNS",
        category: 'সাংস্কৃতিক অনুষ্ঠান',
        performer: 'কে.পি.এন.এস সাংস্কৃতিক শিল্পী ও দল',
        duration: 'YouTube',
        youtubeId: 'ZwCn5FisEz8',
        thumbnailUrl: 'https://img.youtube.com/vi/ZwCn5FisEz8/hqdefault.jpg',
        youtubeUrl: 'https://www.youtube.com/watch?v=ZwCn5FisEz8',
      },
    ],
  },
  {
    bengaliYear: '১৪৩০',
    gregorianYear: 2023,
    edition: '১২তম বর্ষ (12th Year)',
    occasion: 'পহেলা বৈশাখ ১৪৩০ সাংস্কৃতিক সন্ধ্যা ও বৈশাখী মেলা',
    theme: 'ঐতিহ্য, ছন্দ ও মিলনের বৈশাখ',
    venue: 'খেজুরদা মুক্তমঞ্চ, এগরা',
    description: '১৪৩০ বঙ্গাব্দের বর্ণাঢ্য আয়োজনে লোকগীতি, যাত্রাপালা "ভক্ত ও ভগবান", বাউল গান এবং শিশু-কিশোরদের মনোজ্ঞ নৃত্য উপস্থাপনা ছিল অন্যতম আকর্ষণ।',
    playlistUrl: 'https://www.youtube.com/playlist?list=PLo4mBgpHrEi_x92m49LXlYB4v7OKzTvKM',
    playlistThumbnail: 'https://img.youtube.com/vi/xXB1GG02Dy0/hqdefault.jpg',
    videos: [
      {
        id: 'b১৪৩০-1',
        title: "যাত্রাপালা \"ভক্ত ও ভগবান\" || বৈশাখী মেলা ১৪৩০ || KPNS",
        bengaliTitle: "যাত্রাপালা \"ভক্ত ও ভগবান\" || বৈশাখী মেলা ১৪৩০ || KPNS",
        category: 'নাট্য ও যাত্রা',
        performer: 'কে.পি.এন.এস সাংস্কৃতিক শিল্পী ও দল',
        duration: 'YouTube',
        youtubeId: 'xXB1GG02Dy0',
        thumbnailUrl: 'https://img.youtube.com/vi/xXB1GG02Dy0/hqdefault.jpg',
        youtubeUrl: 'https://www.youtube.com/watch?v=xXB1GG02Dy0',
      },
      {
        id: 'b১৪৩০-2',
        title: "উদ্বোধনী নৃত্য || বৈশাখী মেলা ১৪৩০ || KPNS",
        bengaliTitle: "উদ্বোধনী নৃত্য || বৈশাখী মেলা ১৪৩০ || KPNS",
        category: 'নৃত্য পরিবেশনা',
        performer: 'কে.পি.এন.এস সাংস্কৃতিক শিল্পী ও দল',
        duration: 'YouTube',
        youtubeId: 'gdzaLvGRFb0',
        thumbnailUrl: 'https://img.youtube.com/vi/gdzaLvGRFb0/hqdefault.jpg',
        youtubeUrl: 'https://www.youtube.com/watch?v=gdzaLvGRFb0',
      },
      {
        id: 'b১৪৩০-3',
        title: "Kukur Bajai Tumtumi Banar Bajai | কুকুর বাজায় টুমটুমি বানর বাজায় ঢোল || বৈশাখী মেলা ১৪৩০ || KPNS",
        bengaliTitle: "Kukur Bajai Tumtumi Banar Bajai | কুকুর বাজায় টুমটুমি বানর বাজায় ঢোল || বৈশাখী মেলা ১৪৩০ || KPNS",
        category: 'সাংস্কৃতিক অনুষ্ঠান',
        performer: 'কে.পি.এন.এস সাংস্কৃতিক শিল্পী ও দল',
        duration: 'YouTube',
        youtubeId: 'kvh2_2MbAHI',
        thumbnailUrl: 'https://img.youtube.com/vi/kvh2_2MbAHI/hqdefault.jpg',
        youtubeUrl: 'https://www.youtube.com/watch?v=kvh2_2MbAHI',
      },
      {
        id: 'b১৪৩০-4',
        title: "Aye Bristi Jhepe | আয় বৃষ্টি ঝেপে | || বৈশাখী মেলা ১৪৩০ || KPNS",
        bengaliTitle: "Aye Bristi Jhepe | আয় বৃষ্টি ঝেপে | || বৈশাখী মেলা ১৪৩০ || KPNS",
        category: 'সাংস্কৃতিক অনুষ্ঠান',
        performer: 'কে.পি.এন.এস সাংস্কৃতিক শিল্পী ও দল',
        duration: 'YouTube',
        youtubeId: 'AYwqaIC1It8',
        thumbnailUrl: 'https://img.youtube.com/vi/AYwqaIC1It8/hqdefault.jpg',
        youtubeUrl: 'https://www.youtube.com/watch?v=AYwqaIC1It8',
      },
      {
        id: 'b১৪৩০-5',
        title: "Esho Shyamalo Sundaro | এসো শ্যামল সুন্দর || বৈশাখী মেলা ১৪৩০ || KPNS",
        bengaliTitle: "Esho Shyamalo Sundaro | এসো শ্যামল সুন্দর || বৈশাখী মেলা ১৪৩০ || KPNS",
        category: 'সাংস্কৃতিক অনুষ্ঠান',
        performer: 'কে.পি.এন.এস সাংস্কৃতিক শিল্পী ও দল',
        duration: 'YouTube',
        youtubeId: 'bN5QXJjVtek',
        thumbnailUrl: 'https://img.youtube.com/vi/bN5QXJjVtek/hqdefault.jpg',
        youtubeUrl: 'https://www.youtube.com/watch?v=bN5QXJjVtek',
      },
      {
        id: 'b১৪৩০-6',
        title: "Jhuti Badha Kakatua | ঝুটি বাঁধা কাকাতুয়া || বৈশাখী মেলা ১৪৩০ | KPNS",
        bengaliTitle: "Jhuti Badha Kakatua | ঝুটি বাঁধা কাকাতুয়া || বৈশাখী মেলা ১৪৩০ | KPNS",
        category: 'সাংস্কৃতিক অনুষ্ঠান',
        performer: 'কে.পি.এন.এস সাংস্কৃতিক শিল্পী ও দল',
        duration: 'YouTube',
        youtubeId: 'gnOOzk9QDQs',
        thumbnailUrl: 'https://img.youtube.com/vi/gnOOzk9QDQs/hqdefault.jpg',
        youtubeUrl: 'https://www.youtube.com/watch?v=gnOOzk9QDQs',
      },
      {
        id: 'b১৪৩০-7',
        title: "Maine Payal Hai Chhankai || বৈশাখী মেলা ১৪৩০ | KPNS",
        bengaliTitle: "Maine Payal Hai Chhankai || বৈশাখী মেলা ১৪৩০ | KPNS",
        category: 'সাংস্কৃতিক অনুষ্ঠান',
        performer: 'কে.পি.এন.এস সাংস্কৃতিক শিল্পী ও দল',
        duration: 'YouTube',
        youtubeId: 'M0Ov1fX7IuA',
        thumbnailUrl: 'https://img.youtube.com/vi/M0Ov1fX7IuA/hqdefault.jpg',
        youtubeUrl: 'https://www.youtube.com/watch?v=M0Ov1fX7IuA',
      },
      {
        id: 'b১৪৩০-8',
        title: "Nanga Punga Dost || বৈশাখী মেলা ১৪৩০ | KPNS",
        bengaliTitle: "Nanga Punga Dost || বৈশাখী মেলা ১৪৩০ | KPNS",
        category: 'সাংস্কৃতিক অনুষ্ঠান',
        performer: 'কে.পি.এন.এস সাংস্কৃতিক শিল্পী ও দল',
        duration: 'YouTube',
        youtubeId: 'aEzxUtf3Lc8',
        thumbnailUrl: 'https://img.youtube.com/vi/aEzxUtf3Lc8/hqdefault.jpg',
        youtubeUrl: 'https://www.youtube.com/watch?v=aEzxUtf3Lc8',
      },
    ],
  },
  {
    bengaliYear: '১৪২৯',
    gregorianYear: 2022,
    edition: '১১তম বর্ষ (11th Year)',
    occasion: '১৪২৯ বৈশাখী পুনর্মিলনী উৎসব',
    theme: 'নব আনন্দে জাগো নব আনন্দে',
    venue: 'কে.পি.এন.এস ভবন প্রাঙ্গণ',
    description: 'করোনাত্তোর নতুন সূর্যের কিরণে মুখরিত নববর্ষের এই সন্ধ্যায় এলাকার সকল বয়সের মানুষের পদচারণায় এক প্রাণের মেলা তৈরি হয়েছিল।',
    playlistUrl: 'https://www.youtube.com/@kpns1935/playlists',
    playlistThumbnail: 'https://img.youtube.com/vi/oquLVZgywSg/hqdefault.jpg',
    videos: [
    ],
  },
  {
    bengaliYear: '১৪২৮',
    gregorianYear: 2021,
    edition: '১০ম বর্ষ (10th Year - দশম পূর্তি)',
    occasion: 'বৈশাখী সন্ধ্যার এক দশক পূর্তি উৎসব',
    theme: 'এক দশক ধরে সংস্কৃতির দীপশিখা',
    venue: 'খেজুরদা মঞ্চ',
    description: '১৪১৯ থেকে শুরু হওয়া এই সাংস্কৃতিক পরিক্রমার ১০ বছর পূর্তিতে প্রতিষ্ঠাতা শিল্পীদের শ্রদ্ধা ও বিশেষ সংবর্ধনা প্রদান করা হয়।',
    playlistUrl: 'https://www.youtube.com/@kpns1935/playlists',
    playlistThumbnail: 'https://img.youtube.com/vi/oquLVZgywSg/hqdefault.jpg',
    videos: [
    ],
  },
  {
    bengaliYear: '১৪২৭',
    gregorianYear: 2020,
    edition: '৯ম বর্ষ (9th Year)',
    occasion: '১৪২৭ বৈশাখী ঘরোয়া সাংস্কৃতিক সন্ধ্যা',
    theme: 'সংকটেও সংস্কৃতির জয়গান',
    venue: 'খেজুরদা ক্লাব ভবন',
    description: 'লকডাউনের কঠিন সময়ে সীমিত পরিসরে প্রদীপ প্রজ্বলন ও ডিজিটাল মাধ্যমে সঙ্গীত সম্প্রচারের মাধ্যমে ঐতিহ্য অব্যাহত রাখা হয়।',
    playlistUrl: 'https://www.youtube.com/@kpns1935/playlists',
    playlistThumbnail: 'https://img.youtube.com/vi/oquLVZgywSg/hqdefault.jpg',
    videos: [
    ],
  },
  {
    bengaliYear: '১৪২৬',
    gregorianYear: 2019,
    edition: '৮ম বর্ষ (8th Year)',
    occasion: 'বৈশাখী মেলা ও সাংস্কৃতিক নিশি',
    theme: 'মেঠো সুরের মায়াজালে নববর্ষ',
    venue: 'খেজুরদা মুক্তমঞ্চ',
    description: 'পল্লী মেদিনীপুরের প্রাচীন লোকসংস্কৃতি, সরস্বতী বন্দনা, ঘুমুর ও বাউল নাচের বর্ণিল সমারোহে মুখরিত ছিল এই উৎসব।',
    playlistUrl: 'https://www.youtube.com/playlist?list=PLo4mBgpHrEi80wISSFtUInRV1gQu3to9y',
    playlistThumbnail: 'https://img.youtube.com/vi/QmR22yLsPwo/hqdefault.jpg',
    videos: [
      {
        id: 'b১৪২৬-1',
        title: "Saraswati Vandana",
        bengaliTitle: "Saraswati Vandana",
        category: 'সাংস্কৃতিক অনুষ্ঠান',
        performer: 'কে.পি.এন.এস সাংস্কৃতিক শিল্পী ও দল',
        duration: 'YouTube',
        youtubeId: 'QmR22yLsPwo',
        thumbnailUrl: 'https://img.youtube.com/vi/QmR22yLsPwo/hqdefault.jpg',
        youtubeUrl: 'https://www.youtube.com/watch?v=QmR22yLsPwo',
      },
      {
        id: 'b১৪২৬-2',
        title: "Borisho Dhora Majhe Shantir Bari",
        bengaliTitle: "Borisho Dhora Majhe Shantir Bari",
        category: 'সাংস্কৃতিক অনুষ্ঠান',
        performer: 'কে.পি.এন.এস সাংস্কৃতিক শিল্পী ও দল',
        duration: 'YouTube',
        youtubeId: '8nsZOU-dEJU',
        thumbnailUrl: 'https://img.youtube.com/vi/8nsZOU-dEJU/hqdefault.jpg',
        youtubeUrl: 'https://www.youtube.com/watch?v=8nsZOU-dEJU',
      },
      {
        id: 'b১৪২৬-3',
        title: "Mashup Dance",
        bengaliTitle: "Mashup Dance",
        category: 'সাংস্কৃতিক অনুষ্ঠান',
        performer: 'কে.পি.এন.এস সাংস্কৃতিক শিল্পী ও দল',
        duration: 'YouTube',
        youtubeId: 'IaPTKmwtvYw',
        thumbnailUrl: 'https://img.youtube.com/vi/IaPTKmwtvYw/hqdefault.jpg',
        youtubeUrl: 'https://www.youtube.com/watch?v=IaPTKmwtvYw',
      },
      {
        id: 'b১৪২৬-4',
        title: "Tin Dana Tin Dana",
        bengaliTitle: "Tin Dana Tin Dana",
        category: 'সাংস্কৃতিক অনুষ্ঠান',
        performer: 'কে.পি.এন.এস সাংস্কৃতিক শিল্পী ও দল',
        duration: 'YouTube',
        youtubeId: 'bQdNvXTr_Zc',
        thumbnailUrl: 'https://img.youtube.com/vi/bQdNvXTr_Zc/hqdefault.jpg',
        youtubeUrl: 'https://www.youtube.com/watch?v=bQdNvXTr_Zc',
      },
      {
        id: 'b১৪২৬-5',
        title: "Kalo Jole Kuchla Tole",
        bengaliTitle: "Kalo Jole Kuchla Tole",
        category: 'সাংস্কৃতিক অনুষ্ঠান',
        performer: 'কে.পি.এন.এস সাংস্কৃতিক শিল্পী ও দল',
        duration: 'YouTube',
        youtubeId: '6QpPPVRDf5E',
        thumbnailUrl: 'https://img.youtube.com/vi/6QpPPVRDf5E/hqdefault.jpg',
        youtubeUrl: 'https://www.youtube.com/watch?v=6QpPPVRDf5E',
      },
      {
        id: 'b১৪২৬-6',
        title: "Udi Udi Jaye",
        bengaliTitle: "Udi Udi Jaye",
        category: 'সাংস্কৃতিক অনুষ্ঠান',
        performer: 'কে.পি.এন.এস সাংস্কৃতিক শিল্পী ও দল',
        duration: 'YouTube',
        youtubeId: 'EuEhPTG_c0o',
        thumbnailUrl: 'https://img.youtube.com/vi/EuEhPTG_c0o/hqdefault.jpg',
        youtubeUrl: 'https://www.youtube.com/watch?v=EuEhPTG_c0o',
      },
      {
        id: 'b১৪২৬-7',
        title: "Gum Gum Gum Megh Oi Garjay & Allah Megh De Pani De",
        bengaliTitle: "Gum Gum Gum Megh Oi Garjay & Allah Megh De Pani De",
        category: 'সাংস্কৃতিক অনুষ্ঠান',
        performer: 'কে.পি.এন.এস সাংস্কৃতিক শিল্পী ও দল',
        duration: 'YouTube',
        youtubeId: 'tv4QOSj_ERU',
        thumbnailUrl: 'https://img.youtube.com/vi/tv4QOSj_ERU/hqdefault.jpg',
        youtubeUrl: 'https://www.youtube.com/watch?v=tv4QOSj_ERU',
      },
      {
        id: 'b১৪২৬-8',
        title: "Ghoomar & Nagada Sang Dhol",
        bengaliTitle: "Ghoomar & Nagada Sang Dhol",
        category: 'সাংস্কৃতিক অনুষ্ঠান',
        performer: 'কে.পি.এন.এস সাংস্কৃতিক শিল্পী ও দল',
        duration: 'YouTube',
        youtubeId: 'tu9ZUMFrzBY',
        thumbnailUrl: 'https://img.youtube.com/vi/tu9ZUMFrzBY/hqdefault.jpg',
        youtubeUrl: 'https://www.youtube.com/watch?v=tu9ZUMFrzBY',
      },
    ],
  },
  {
    bengaliYear: '১৪২৫',
    gregorianYear: 2018,
    edition: '৭ম বর্ষ (7th Year)',
    occasion: 'শুভ নববর্ষ ১৪২৫ সাংস্কৃতিক আসর',
    theme: 'সবার পরশে পবিত্র করা তীর্থনীরে',
    venue: 'খেজুরদা নারায়ণ সংঘ প্রাঙ্গণ',
    description: 'নৃত্য, গান ও হাস্যরসাত্মক একাঙ্ক নাটকের পরিবেশনায় মধ্যরাত পর্যন্ত দর্শকেরা মন্ত্রমুগ্ধের মতো উপভোগ করেন।',
    playlistUrl: 'https://www.youtube.com/@kpns1935/playlists',
    playlistThumbnail: 'https://img.youtube.com/vi/oquLVZgywSg/hqdefault.jpg',
    videos: [
    ],
  },
  {
    bengaliYear: '১৪২৪',
    gregorianYear: 2017,
    edition: '৬ষ্ঠ বর্ষ (6th Year)',
    occasion: 'বৈশাখী সন্ধ্যা ১৪২৪',
    theme: 'রক্তিম পলাশ ও পল্লী উৎসব',
    venue: 'খেজুরদা মুক্তমঞ্চ',
    description: 'নতুন প্রজন্মের কিশোর-কিশোরীদের গান ও শাস্ত্রীয় নৃত্য পরিবেশনা বিশেষভাবে প্রশংসিত হয়।',
    playlistUrl: 'https://www.youtube.com/playlist?list=PLo4mBgpHrEi-zIjAnmn-B5RWpI8Y2_wWP',
    playlistThumbnail: 'https://img.youtube.com/vi/cEUuR3rY6P4/hqdefault.jpg',
    videos: [
      {
        id: 'b১৪২৪-1',
        title: "BOISHAKHI SONDHA - 1424",
        bengaliTitle: "BOISHAKHI SONDHA - 1424",
        category: 'সাংস্কৃতিক অনুষ্ঠান',
        performer: 'কে.পি.এন.এস সাংস্কৃতিক শিল্পী ও দল',
        duration: 'YouTube',
        youtubeId: 'cEUuR3rY6P4',
        thumbnailUrl: 'https://img.youtube.com/vi/cEUuR3rY6P4/hqdefault.jpg',
        youtubeUrl: 'https://www.youtube.com/watch?v=cEUuR3rY6P4',
      },
    ],
  },
  {
    bengaliYear: '১৪২৩',
    gregorianYear: 2016,
    edition: '৫ম বর্ষ (5th Year - পঞ্চম পূর্তি)',
    occasion: 'বৈশাখী সন্ধ্যার পঞ্চম পূর্তি মহোৎসব',
    theme: 'পঞ্চম বর্ষে নব উল্লাসে',
    venue: 'কে.পি.এন.এস উৎসব প্রাঙ্গণ',
    description: 'পাঁচ বছর সফল উদযাপনের স্মারক হিসেবে বিশেষ সংকলন ও স্থানীয় গুণী ব্যক্তিত্বদের সম্মানিত করা হয়।',
    playlistUrl: 'https://www.youtube.com/@kpns1935/playlists',
    playlistThumbnail: 'https://img.youtube.com/vi/oquLVZgywSg/hqdefault.jpg',
    videos: [
    ],
  },
  {
    bengaliYear: '১৪২২',
    gregorianYear: 2015,
    edition: '৪র্থ বর্ষ (4th Year)',
    occasion: 'বৈশাখী সন্ধ্যা ১৪২২',
    theme: 'পল্লী সুরের ঝরনাধারা',
    venue: 'খেজুরদা মঞ্চ',
    description: 'পল্লীগীতি ও আধুনিক বাংলা গানের এক অপূর্ব সম্মিলন ঘটেছিল এই বৈশাখী নিশীথে।',
    playlistUrl: 'https://www.youtube.com/@kpns1935/playlists',
    playlistThumbnail: 'https://img.youtube.com/vi/oquLVZgywSg/hqdefault.jpg',
    videos: [
    ],
  },
  {
    bengaliYear: '১৪২১',
    gregorianYear: 2014,
    edition: '৩য় বর্ষ (3rd Year)',
    occasion: 'বৈশাখী সন্ধ্যা ১৪২১',
    theme: 'বাংলার সংস্কৃতি চির অমলিন',
    venue: 'খেজুরদা সংঘ মুক্তমঞ্চ',
    description: 'লোকনাট্য, দেশাত্মবোধক গান ও লোকনৃত্যের সুর গ্রামবাংলায় প্রাণের স্পন্দন সঞ্চার করেছিল।',
    playlistUrl: 'https://www.youtube.com/playlist?list=PLo4mBgpHrEi_mJ6-q-Q-mxezzH1PWEjzz',
    playlistThumbnail: 'https://img.youtube.com/vi/tNOMrvWVlkU/hqdefault.jpg',
    videos: [
      {
        id: 'b১৪২১-1',
        title: "Jhum Jhum Jhumra Nach Neche Ke Elo Go",
        bengaliTitle: "Jhum Jhum Jhumra Nach Neche Ke Elo Go",
        category: 'সাংস্কৃতিক অনুষ্ঠান',
        performer: 'কে.পি.এন.এস সাংস্কৃতিক শিল্পী ও দল',
        duration: 'YouTube',
        youtubeId: 'tNOMrvWVlkU',
        thumbnailUrl: 'https://img.youtube.com/vi/tNOMrvWVlkU/hqdefault.jpg',
        youtubeUrl: 'https://www.youtube.com/watch?v=tNOMrvWVlkU',
      },
      {
        id: 'b১৪২১-2',
        title: "Police Pore Jaay Chintaay",
        bengaliTitle: "Police Pore Jaay Chintaay",
        category: 'সাংস্কৃতিক অনুষ্ঠান',
        performer: 'কে.পি.এন.এস সাংস্কৃতিক শিল্পী ও দল',
        duration: 'YouTube',
        youtubeId: 'rXJxlu2_oEE',
        thumbnailUrl: 'https://img.youtube.com/vi/rXJxlu2_oEE/hqdefault.jpg',
        youtubeUrl: 'https://www.youtube.com/watch?v=rXJxlu2_oEE',
      },
      {
        id: 'b১৪২১-3',
        title: "MONO MOR MEGHER SANGI",
        bengaliTitle: "MONO MOR MEGHER SANGI",
        category: 'সাংস্কৃতিক অনুষ্ঠান',
        performer: 'কে.পি.এন.এস সাংস্কৃতিক শিল্পী ও দল',
        duration: 'YouTube',
        youtubeId: '0-9kjrSjatY',
        thumbnailUrl: 'https://img.youtube.com/vi/0-9kjrSjatY/hqdefault.jpg',
        youtubeUrl: 'https://www.youtube.com/watch?v=0-9kjrSjatY',
      },
      {
        id: 'b১৪২১-4',
        title: "Tapur tupur sara dupur nupur bajay ke",
        bengaliTitle: "Tapur tupur sara dupur nupur bajay ke",
        category: 'সাংস্কৃতিক অনুষ্ঠান',
        performer: 'কে.পি.এন.এস সাংস্কৃতিক শিল্পী ও দল',
        duration: 'YouTube',
        youtubeId: 'tUYBbYsIcsM',
        thumbnailUrl: 'https://img.youtube.com/vi/tUYBbYsIcsM/hqdefault.jpg',
        youtubeUrl: 'https://www.youtube.com/watch?v=tUYBbYsIcsM',
      },
      {
        id: 'b১৪২১-5',
        title: "Tamasa Chhailo Jibone",
        bengaliTitle: "Tamasa Chhailo Jibone",
        category: 'সাংস্কৃতিক অনুষ্ঠান',
        performer: 'কে.পি.এন.এস সাংস্কৃতিক শিল্পী ও দল',
        duration: 'YouTube',
        youtubeId: 'bSyZno5i8Yg',
        thumbnailUrl: 'https://img.youtube.com/vi/bSyZno5i8Yg/hqdefault.jpg',
        youtubeUrl: 'https://www.youtube.com/watch?v=bSyZno5i8Yg',
      },
      {
        id: 'b১৪২১-6',
        title: "Desh Mera Rangeela",
        bengaliTitle: "Desh Mera Rangeela",
        category: 'সাংস্কৃতিক অনুষ্ঠান',
        performer: 'কে.পি.এন.এস সাংস্কৃতিক শিল্পী ও দল',
        duration: 'YouTube',
        youtubeId: '7bCEzj8OXrE',
        thumbnailUrl: 'https://img.youtube.com/vi/7bCEzj8OXrE/hqdefault.jpg',
        youtubeUrl: 'https://www.youtube.com/watch?v=7bCEzj8OXrE',
      },
      {
        id: 'b১৪২১-7',
        title: "I LOVE MY INDIA",
        bengaliTitle: "I LOVE MY INDIA",
        category: 'সাংস্কৃতিক অনুষ্ঠান',
        performer: 'কে.পি.এন.এস সাংস্কৃতিক শিল্পী ও দল',
        duration: 'YouTube',
        youtubeId: '1jjZObC6abQ',
        thumbnailUrl: 'https://img.youtube.com/vi/1jjZObC6abQ/hqdefault.jpg',
        youtubeUrl: 'https://www.youtube.com/watch?v=1jjZObC6abQ',
      },
      {
        id: 'b১৪২১-8',
        title: "Dola He Dola",
        bengaliTitle: "Dola He Dola",
        category: 'সাংস্কৃতিক অনুষ্ঠান',
        performer: 'কে.পি.এন.এস সাংস্কৃতিক শিল্পী ও দল',
        duration: 'YouTube',
        youtubeId: 'sCqBxu-z3CA',
        thumbnailUrl: 'https://img.youtube.com/vi/sCqBxu-z3CA/hqdefault.jpg',
        youtubeUrl: 'https://www.youtube.com/watch?v=sCqBxu-z3CA',
      },
    ],
  },
  {
    bengaliYear: '১৪২০',
    gregorianYear: 2013,
    edition: '২য় বর্ষ (2nd Year)',
    occasion: 'বৈশাখী সন্ধ্যা ১৪২০',
    theme: 'প্রাণের মেলা সংস্কৃতির মেলা',
    venue: 'খেজুরদা নারায়ণ সংঘ প্রাঙ্গণ',
    description: 'প্রথম বর্ষের বিপুল উদ্দীপনার পর দ্বিতীয় বর্ষে আরও বৃহত্তর মঞ্চে বিপুল সমাগমে উদযাপিত হয়।',
    playlistUrl: 'https://www.youtube.com/playlist?list=PLo4mBgpHrEi8w_HZ6zPqK0et4KlH1Rve9',
    playlistThumbnail: 'https://img.youtube.com/vi/NZH1hc_GGf4/hqdefault.jpg',
    videos: [
      {
        id: 'b১৪২০-1',
        title: "Tu Kene Kada Dili Sada Kapore",
        bengaliTitle: "Tu Kene Kada Dili Sada Kapore",
        category: 'সাংস্কৃতিক অনুষ্ঠান',
        performer: 'কে.পি.এন.এস সাংস্কৃতিক শিল্পী ও দল',
        duration: 'YouTube',
        youtubeId: 'NZH1hc_GGf4',
        thumbnailUrl: 'https://img.youtube.com/vi/NZH1hc_GGf4/hqdefault.jpg',
        youtubeUrl: 'https://www.youtube.com/watch?v=NZH1hc_GGf4',
      },
      {
        id: 'b১৪২০-2',
        title: "Sar Pe Himalaya Ka Chhatra hai",
        bengaliTitle: "Sar Pe Himalaya Ka Chhatra hai",
        category: 'সাংস্কৃতিক অনুষ্ঠান',
        performer: 'কে.পি.এন.এস সাংস্কৃতিক শিল্পী ও দল',
        duration: 'YouTube',
        youtubeId: 'jMBmu7E458I',
        thumbnailUrl: 'https://img.youtube.com/vi/jMBmu7E458I/hqdefault.jpg',
        youtubeUrl: 'https://www.youtube.com/watch?v=jMBmu7E458I',
      },
      {
        id: 'b১৪২০-3',
        title: "Projapoti E Mon Meluk Pakhna",
        bengaliTitle: "Projapoti E Mon Meluk Pakhna",
        category: 'সাংস্কৃতিক অনুষ্ঠান',
        performer: 'কে.পি.এন.এস সাংস্কৃতিক শিল্পী ও দল',
        duration: 'YouTube',
        youtubeId: 'hIX1yhR3RT8',
        thumbnailUrl: 'https://img.youtube.com/vi/hIX1yhR3RT8/hqdefault.jpg',
        youtubeUrl: 'https://www.youtube.com/watch?v=hIX1yhR3RT8',
      },
      {
        id: 'b১৪২০-4',
        title: "Main Toh Aarati Utaru Re Santoshi Mata Ki",
        bengaliTitle: "Main Toh Aarati Utaru Re Santoshi Mata Ki",
        category: 'সাংস্কৃতিক অনুষ্ঠান',
        performer: 'কে.পি.এন.এস সাংস্কৃতিক শিল্পী ও দল',
        duration: 'YouTube',
        youtubeId: 'mypS-9wfGGI',
        thumbnailUrl: 'https://img.youtube.com/vi/mypS-9wfGGI/hqdefault.jpg',
        youtubeUrl: 'https://www.youtube.com/watch?v=mypS-9wfGGI',
      },
      {
        id: 'b১৪২০-5',
        title: "Chhoti Si Pyari Si",
        bengaliTitle: "Chhoti Si Pyari Si",
        category: 'সাংস্কৃতিক অনুষ্ঠান',
        performer: 'কে.পি.এন.এস সাংস্কৃতিক শিল্পী ও দল',
        duration: 'YouTube',
        youtubeId: 'Zno6OuTuJGk',
        thumbnailUrl: 'https://img.youtube.com/vi/Zno6OuTuJGk/hqdefault.jpg',
        youtubeUrl: 'https://www.youtube.com/watch?v=Zno6OuTuJGk',
      },
      {
        id: 'b১৪২০-6',
        title: "Chanda Chamke Cham Cham",
        bengaliTitle: "Chanda Chamke Cham Cham",
        category: 'সাংস্কৃতিক অনুষ্ঠান',
        performer: 'কে.পি.এন.এস সাংস্কৃতিক শিল্পী ও দল',
        duration: 'YouTube',
        youtubeId: 'aUuwm-AmhDw',
        thumbnailUrl: 'https://img.youtube.com/vi/aUuwm-AmhDw/hqdefault.jpg',
        youtubeUrl: 'https://www.youtube.com/watch?v=aUuwm-AmhDw',
      },
      {
        id: 'b১৪২০-7',
        title: "Hante sishu chhote",
        bengaliTitle: "Hante sishu chhote",
        category: 'সাংস্কৃতিক অনুষ্ঠান',
        performer: 'কে.পি.এন.এস সাংস্কৃতিক শিল্পী ও দল',
        duration: 'YouTube',
        youtubeId: 'jsoY2ept2Kg',
        thumbnailUrl: 'https://img.youtube.com/vi/jsoY2ept2Kg/hqdefault.jpg',
        youtubeUrl: 'https://www.youtube.com/watch?v=jsoY2ept2Kg',
      },
      {
        id: 'b১৪২০-8',
        title: "Jago Natun Prabhat Jago",
        bengaliTitle: "Jago Natun Prabhat Jago",
        category: 'সাংস্কৃতিক অনুষ্ঠান',
        performer: 'কে.পি.এন.এস সাংস্কৃতিক শিল্পী ও দল',
        duration: 'YouTube',
        youtubeId: 'iGz0ELdYtLc',
        thumbnailUrl: 'https://img.youtube.com/vi/iGz0ELdYtLc/hqdefault.jpg',
        youtubeUrl: 'https://www.youtube.com/watch?v=iGz0ELdYtLc',
      },
    ],
  },
  {
    bengaliYear: '১৪১৯',
    gregorianYear: 2012,
    edition: '১ম প্রারম্ভিক বর্ষ (Inaugural Year)',
    occasion: 'ঐতিহাসিক শুভ সূচনা — প্রথম বৈশাখী সন্ধ্যা ১৪১৯',
    theme: 'বৈশাখী সন্ধ্যার শুভ জন্মদিন',
    venue: 'খেজুরদা নারায়ণ সংঘ প্রাঙ্গণ',
    description: '১৪১৯ বঙ্গাব্দের পহেলা বৈশাখে সূচনা হয়েছিল এক নতুন সাংস্কৃতিক নবজাগরণের। বাংলার সংস্কৃতি, ঐতিহ্য ও লোকজ আনন্দকে কেন্দ্র করে প্রতি বছর এই মিলনযজ্ঞ অব্যাহত রাখার শপথ গ্রহণ করা হয়।',
    playlistUrl: 'https://www.youtube.com/playlist?list=PL1CD37C543400B4A4',
    playlistThumbnail: 'https://img.youtube.com/vi/lz6_xqoUAU8/hqdefault.jpg',
    videos: [
      {
        id: 'b১৪১৯-1',
        title: "Baburam Shapure(Remix).flv",
        bengaliTitle: "Baburam Shapure(Remix).flv",
        category: 'সাংস্কৃতিক অনুষ্ঠান',
        performer: 'কে.পি.এন.এস সাংস্কৃতিক শিল্পী ও দল',
        duration: 'YouTube',
        youtubeId: 'lz6_xqoUAU8',
        thumbnailUrl: 'https://img.youtube.com/vi/lz6_xqoUAU8/hqdefault.jpg',
        youtubeUrl: 'https://www.youtube.com/watch?v=lz6_xqoUAU8',
      },
      {
        id: 'b১৪১৯-2',
        title: "Dhitang Dhitang Bole.flv",
        bengaliTitle: "Dhitang Dhitang Bole.flv",
        category: 'সাংস্কৃতিক অনুষ্ঠান',
        performer: 'কে.পি.এন.এস সাংস্কৃতিক শিল্পী ও দল',
        duration: 'YouTube',
        youtubeId: 'fGJxYE_Ci5U',
        thumbnailUrl: 'https://img.youtube.com/vi/fGJxYE_Ci5U/hqdefault.jpg',
        youtubeUrl: 'https://www.youtube.com/watch?v=fGJxYE_Ci5U',
      },
      {
        id: 'b১৪১৯-3',
        title: "Jhun Jhun Moyna Nacho Na.flv",
        bengaliTitle: "Jhun Jhun Moyna Nacho Na.flv",
        category: 'সাংস্কৃতিক অনুষ্ঠান',
        performer: 'কে.পি.এন.এস সাংস্কৃতিক শিল্পী ও দল',
        duration: 'YouTube',
        youtubeId: 'h4CZeBfgfK4',
        thumbnailUrl: 'https://img.youtube.com/vi/h4CZeBfgfK4/hqdefault.jpg',
        youtubeUrl: 'https://www.youtube.com/watch?v=h4CZeBfgfK4',
      },
      {
        id: 'b১৪১৯-4',
        title: "Raj rani meera.flv",
        bengaliTitle: "Raj rani meera.flv",
        category: 'সাংস্কৃতিক অনুষ্ঠান',
        performer: 'কে.পি.এন.এস সাংস্কৃতিক শিল্পী ও দল',
        duration: 'YouTube',
        youtubeId: 'Azni3U4xUdg',
        thumbnailUrl: 'https://img.youtube.com/vi/Azni3U4xUdg/hqdefault.jpg',
        youtubeUrl: 'https://www.youtube.com/watch?v=Azni3U4xUdg',
      },
      {
        id: 'b১৪১৯-5',
        title: "DSCN0015",
        bengaliTitle: "DSCN0015",
        category: 'সাংস্কৃতিক অনুষ্ঠান',
        performer: 'কে.পি.এন.এস সাংস্কৃতিক শিল্পী ও দল',
        duration: 'YouTube',
        youtubeId: 'hZsxMWKga0w',
        thumbnailUrl: 'https://img.youtube.com/vi/hZsxMWKga0w/hqdefault.jpg',
        youtubeUrl: 'https://www.youtube.com/watch?v=hZsxMWKga0w',
      },
    ],
  },
];
